apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-webui.name" . }}
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
    {{- with .Values.webui.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.webui.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "open-webui.selectorLabels" . | nindent 4 }}
  type: {{ .Values.webui.service.type | default "ClusterIP" }}
  ports:
  - protocol: TCP
    name: http
    port: {{ .Values.webui.service.port }}
    targetPort: http
    {{- if .Values.webui.service.nodePort }}
    nodePort: {{ .Values.webui.service.nodePort | int }}
    {{- end }}
  {{- if .Values.webui.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.webui.service.loadBalancerClass | quote }}
  {{- end }}

